# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Codec',
                'verbose_name_plural': 'Codecs',
            },
        ),
        migrations.CreateModel(
            name='DeliveryContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Delivery Context',
                'verbose_name_plural': 'Delivery Contexts',
            },
        ),
        migrations.CreateModel(
            name='DeliveryProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpmn', models.CharField(max_length=256)),
                ('delivery_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=1024, null=True)),
                ('receipt_acknowledgement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Delivery Process',
                'verbose_name_plural': 'Delivery Processes',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Entity Type',
                'verbose_name_plural': 'Entity Types',
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Image Type',
                'verbose_name_plural': 'Image Types',
            },
        ),
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(max_length=256)),
                ('xform', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Metadata Schema',
                'verbose_name_plural': 'Metadata Schemas',
            },
        ),
        migrations.CreateModel(
            name='PackageStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_template', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Package Structure',
                'verbose_name_plural': 'Package Structures',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='ScanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Scan Type',
                'verbose_name_plural': 'Scan Types',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
            },
        ),
        migrations.CreateModel(
            name='StaticImageRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_content_relationship', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(max_length=256)),
                ('image_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epd.ImageType')),
            ],
            options={
                'verbose_name': 'Static Image Requirement',
                'verbose_name_plural': 'Static Image Requirements',
            },
        ),
        migrations.CreateModel(
            name='TechnicalVideoRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_average_bitrate', models.FloatField(blank=True, null=True)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('audio_sample_rate', models.IntegerField(blank=True, null=True)),
                ('audio_bit_depth', models.IntegerField(blank=True, null=True)),
                ('audio_channels', models.IntegerField(blank=True, null=True)),
                ('audio_channel_configuration', models.CharField(blank=True, max_length=256, null=True)),
                ('x_pixels_per_inch', models.IntegerField(blank=True, null=True)),
                ('y_pixels_per_inch', models.IntegerField(blank=True, null=True)),
                ('audio_track_configuration', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(max_length=256)),
                ('codec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epd.Codec')),
                ('scan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epd.ScanType')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epd.Specification')),
            ],
            options={
                'verbose_name': 'Technical Video Requirement',
                'verbose_name_plural': 'Technical Video Requirements',
            },
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='delivery_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.DeliveryProcess'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.Endpoint'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.EntityType'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='image_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.StaticImageRequirements'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='metadata_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.MetadataSchema'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='package_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.PackageStructure'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.Platform'),
        ),
        migrations.AddField(
            model_name='deliverycontext',
            name='technical_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd.TechnicalVideoRequirements'),
        ),
    ]
