# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:33
from __future__ import unicode_literals

import core.enums
import core.predicates
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipEpisodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.ClipToEpisodePredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_target', models.CharField(max_length=1024)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.Activity')),
                ('object_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.ObjectProperty')),
            ],
        ),
        migrations.CreateModel(
            name='Endeavor',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Endeavor',
                'ordering': ('vmid',),
                'verbose_name_plural': 'Endeavors',
            },
        ),
        migrations.CreateModel(
            name='EpisodeSeasonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.EpisodeToSeasonPredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleEpisodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.ModuleToEpisodePredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='MovieFranchiseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.MovieToFranchisePredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSeriesRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.SeasonToSeriesPredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesFranchiseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.SeriesToFranchisePredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSeriesRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=0, enum=core.predicates.SpecialToSeriesPredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.CharField(max_length=1056)),
            ],
            options={
                'verbose_name': 'Title',
                'ordering': ('title_text',),
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('length_restriction', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Title Type',
                'ordering': ('name',),
                'verbose_name_plural': 'Title Types',
            },
        ),
        migrations.CreateModel(
            name='VersionEpisodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', django_enumfield.db.fields.EnumField(default=1, enum=core.predicates.VersionToEpisodePredicatesEnum)),
            ],
        ),
        migrations.CreateModel(
            name='ContentContainer',
            fields=[
                ('endeavor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Endeavor')),
                ('default_title', models.CharField(default='title', max_length=255)),
                ('cctype', django_enumfield.db.fields.EnumField(default=0, enum=core.enums.ContainerTypesEnum)),
            ],
            options={
                'verbose_name': 'Content Container',
                'ordering': ('cctype', 'vmid'),
                'verbose_name_plural': 'Content Containers',
            },
            bases=('core.endeavor',),
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('endeavor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Endeavor')),
                ('citype', django_enumfield.db.fields.EnumField(default=0, enum=core.enums.ItemTypesEnum)),
                ('default_title', models.CharField(default='title', max_length=255)),
            ],
            options={
                'verbose_name': 'Content Item',
                'ordering': ('citype', 'vmid'),
                'verbose_name_plural': 'Content Item',
            },
            bases=('core.endeavor',),
        ),
        migrations.AddField(
            model_name='title',
            name='endeavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endeavor'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TitleType'),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refdata.Country'),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='reference_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refdata.Channel'),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentItem')),
            ],
            options={
                'verbose_name': 'Clip',
                'verbose_name_plural': 'Clip',
            },
            bases=('core.contentitem',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentItem')),
                ('typical_length', models.CharField(max_length=12, null=True)),
                ('production_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episode',
            },
            bases=('core.contentitem',),
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('contentcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentContainer')),
            ],
            options={
                'verbose_name': 'Franchise',
                'verbose_name_plural': 'Franchises',
            },
            bases=('core.contentcontainer',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentItem')),
                ('typical_length', models.CharField(max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Module',
            },
            bases=('core.contentitem',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentItem')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movie',
            },
            bases=('core.contentitem',),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('contentcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentContainer')),
                ('number', models.IntegerField(null=True)),
                ('sequence', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Season',
            },
            bases=('core.contentcontainer',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('contentcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentContainer')),
                ('typical_length', models.CharField(max_length=12, null=True)),
                ('reference_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refdata.BCP47Language')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
            bases=('core.contentcontainer',),
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentItem')),
            ],
            options={
                'verbose_name': 'Special',
                'verbose_name_plural': 'Special',
            },
            bases=('core.contentitem',),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContentItem')),
                ('label', models.CharField(default='label', max_length=1024)),
            ],
            options={
                'verbose_name': 'Version',
                'ordering': ('label',),
                'verbose_name_plural': 'Versions',
            },
            bases=('core.contentitem',),
        ),
        migrations.AddField(
            model_name='versionepisoderelation',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Episode'),
        ),
        migrations.AddField(
            model_name='versionepisoderelation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Version'),
        ),
        migrations.AddField(
            model_name='specialseriesrelation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Series'),
        ),
        migrations.AddField(
            model_name='specialseriesrelation',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Special'),
        ),
        migrations.AddField(
            model_name='seriesfranchiserelation',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Franchise'),
        ),
        migrations.AddField(
            model_name='seriesfranchiserelation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Series'),
        ),
        migrations.AddField(
            model_name='seasonseriesrelation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AddField(
            model_name='seasonseriesrelation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Series'),
        ),
        migrations.AddField(
            model_name='moviefranchiserelation',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Franchise'),
        ),
        migrations.AddField(
            model_name='moviefranchiserelation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Movie'),
        ),
        migrations.AddField(
            model_name='moduleepisoderelation',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Episode'),
        ),
        migrations.AddField(
            model_name='moduleepisoderelation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Module'),
        ),
        migrations.AddField(
            model_name='episodeseasonrelation',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Episode'),
        ),
        migrations.AddField(
            model_name='episodeseasonrelation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AddField(
            model_name='customizationspecification',
            name='for_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Version'),
        ),
        migrations.AddField(
            model_name='clipepisoderelation',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Clip'),
        ),
        migrations.AddField(
            model_name='clipepisoderelation',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Episode'),
        ),
    ]
