# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subactivities', to='refdata.Activity')),
            ],
            options={
                'verbose_name': 'Activity',
                'ordering': ('name',),
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityPropertyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.Activity')),
            ],
            options={
                'verbose_name': 'Activity-to-Object Property Relationship',
                'verbose_name_plural': 'Activity-to-Object Property Relationships',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'ordering': ('name',),
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='BCP47Language',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BCP-47 Language',
                'ordering': ('language', 'script', 'country'),
                'verbose_name_plural': 'BCP-47 Languages',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')])),
                ('ebxid', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'ordering': ('short_name',),
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code2', models.CharField(max_length=2)),
                ('code3', models.CharField(max_length=3)),
                ('codeN', models.IntegerField()),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'ordering': ('name',),
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountrySubdivision',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subcode', models.CharField(max_length=3)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.Country')),
            ],
            options={
                'verbose_name': 'Country Subdivision',
                'ordering': ('name',),
                'verbose_name_plural': 'Country Subdivisions',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'ordering': ('name',),
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='GenreAuthority',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ref_link', models.URLField(null=True)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Genre Authority',
                'ordering': ('name',),
                'verbose_name_plural': 'Genre Authorities',
            },
        ),
        migrations.CreateModel(
            name='GenreType',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Genre Type',
                'ordering': ('name',),
                'verbose_name_plural': 'Genre Types',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code2', models.CharField(max_length=2)),
                ('code3', models.CharField(max_length=3)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ('name',),
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='ObjectProperty',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('object_type', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Object Property',
                'ordering': ('name',),
                'verbose_name_plural': 'Object Properties',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rating',
                'ordering': ('name',),
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='RatingAuthority',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('ref_link', models.URLField(null=True)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rating Authority',
                'ordering': ('name',),
                'verbose_name_plural': 'Rating Authorities',
            },
        ),
        migrations.CreateModel(
            name='RatingContentDescriptor',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descriptor', models.CharField(max_length=255)),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content Descriptor',
                'ordering': ('descriptor',),
                'verbose_name_plural': 'Content Descriptors',
            },
        ),
        migrations.CreateModel(
            name='ScriptName',
            fields=[
                ('vmid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=8)),
                ('number', models.IntegerField()),
                ('ebxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Script Name',
                'ordering': ('name',),
                'verbose_name_plural': 'Script Names',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.RatingAuthority'),
        ),
        migrations.AddField(
            model_name='rating',
            name='descriptors',
            field=models.ManyToManyField(blank=True, to='refdata.RatingContentDescriptor'),
        ),
        migrations.AddField(
            model_name='genre',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.GenreAuthority'),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refdata.Genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.GenreType'),
        ),
        migrations.AddField(
            model_name='bcp47language',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.Country'),
        ),
        migrations.AddField(
            model_name='bcp47language',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.Language'),
        ),
        migrations.AddField(
            model_name='bcp47language',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.ScriptName'),
        ),
        migrations.AddField(
            model_name='activitypropertyrelation',
            name='object_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.ObjectProperty'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.ActivityType'),
        ),
    ]
