# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import omf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Deliverable',
                'verbose_name_plural': 'Deliverables',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=256)),
                ('deliverable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='omf.Deliverable')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', django_enumfield.db.fields.EnumField(default=0, enum=omf.models.OrderStates)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=256)),
                ('order_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_for', to='epd.Endpoint')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_order', to='omf.Order')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_to', to='epd.Endpoint')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_enumfield.db.fields.EnumField(default=0, enum=omf.models.LineItemStates)),
                ('headline', models.CharField(max_length=256)),
                ('notes', models.TextField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='omf.Order')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
            },
        ),
        migrations.CreateModel(
            name='OrderPredecessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='omf.Order')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='omf.Order')),
            ],
            options={
                'verbose_name': 'Order Predecessor',
                'verbose_name_plural': 'Order Predecessors',
            },
        ),
        migrations.CreateModel(
            name='OrderPredecessorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Predecessor Type',
                'verbose_name_plural': 'Predecessor Types',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_datetime', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.CharField(max_length=256)),
                ('status_note', models.TextField(null=True)),
                ('status_flag', django_enumfield.db.fields.EnumField(default=0, enum=omf.models.StatusFlags)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='omf.Order')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('parameters', models.TextField()),
            ],
            options={
                'verbose_name': 'Promise',
                'verbose_name_plural': 'Promises',
            },
        ),
        migrations.AddField(
            model_name='orderpredecessor',
            name='predecessor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omf.OrderPredecessorType'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='omf.Order'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='line_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='omf.OrderLineItem'),
        ),
    ]
